/**
 * 拼音工具函数
 * 用于城市搜索的拼音转换
 */

// 常用城市及其拼音首字母和全拼映射
const cityPinyinMap: Record<string, string[]> = {
  // 常用城市
  北京: ["beijing", "bj"],
  上海: ["shanghai", "sh"],
  广州: ["guangzhou", "gz"],
  深圳: ["shenzhen", "sz"],
  成都: ["chengdu", "cd"],
  重庆: ["chongqing", "cq"],
  杭州: ["hangzhou", "hz"],
  武汉: ["wuhan", "wh"],
  西安: ["xian", "xa"],
  南京: ["nanjing", "nj"],
  天津: ["tianjin", "tj"],
  苏州: ["suzhou", "sz"],
  长沙: ["changsha", "cs"],
  郑州: ["zhengzhou", "zz"],
  沈阳: ["shenyang", "sy"],
  青岛: ["qingdao", "qd"],
  大连: ["dalian", "dl"],
  厦门: ["xiamen", "xm"],
  昆明: ["kunming", "km"],
  哈尔滨: ["haerbin", "heb"],
  济南: ["jinan", "jn"],
  合肥: ["hefei", "hf"],
  福州: ["fuzhou", "fz"],
  石家庄: ["shijiazhuang", "sjz"],
  太原: ["taiyuan", "ty"],
  南昌: ["nanchang", "nc"],
  南宁: ["nanning", "nn"],
  海口: ["haikou", "hk"],
  乌鲁木齐: ["wulumuqi", "wlmq"],
  兰州: ["lanzhou", "lz"],
  银川: ["yinchuan", "yc"],
  西宁: ["xining", "xn"],
  拉萨: ["lasa", "ls"],
  呼和浩特: ["huhehaote", "hhht"],
  
  // 其他城市
  无锡: ["wuxi", "wx"],
  佛山: ["foshan", "fs"],
  东莞: ["dongguan", "dg"],
  宁波: ["ningbo", "nb"],
  温州: ["wenzhou", "wz"],
  常州: ["changzhou", "cz"],
  珠海: ["zhuhai", "zh"],
  中山: ["zhongshan", "zs"],
  烟台: ["yantai", "yt"],
  泉州: ["quanzhou", "qz"],
  台州: ["taizhou", "tz"],
  嘉兴: ["jiaxing", "jx"],
  绍兴: ["shaoxing", "sx"],
  湖州: ["huzhou", "hz"],
  金华: ["jinhua", "jh"],
  镇江: ["zhenjiang", "zj"],
  扬州: ["yangzhou", "yz"],
  泰州: ["taizhou", "tz"],
  盐城: ["yancheng", "yc"],
  南通: ["nantong", "nt"],
  淮安: ["huaian", "ha"],
  宿迁: ["suqian", "sq"],
  连云港: ["lianyungang", "lyg"],
  徐州: ["xuzhou", "xz"],
  临沂: ["linyi", "ly"],
  济宁: ["jining", "jn"],
  菏泽: ["heze", "hz"],
  聊城: ["liaocheng", "lc"],
  德州: ["dezhou", "dz"],
  东营: ["dongying", "dy"],
  潍坊: ["weifang", "wf"],
  淄博: ["zibo", "zb"],
  日照: ["rizhao", "rz"],
  威海: ["weihai", "wh"],
  滨州: ["binzhou", "bz"],
  枣庄: ["zaozhuang", "zz"],
  泰安: ["taian", "ta"],
  莱芜: ["laiwu", "lw"],
  攀枝花: ["panzhihua", "pzh"],
  绵阳: ["mianyang", "my"],
  南充: ["nanchong", "nc"],
  乐山: ["leshan", "ls"],
  自贡: ["zigong", "zg"],
  泸州: ["luzhou", "lz"],
  德阳: ["deyang", "dy"],
  宜宾: ["yibin", "yb"],
  内江: ["neijiang", "nj"],
  遂宁: ["suining", "sn"],
  达州: ["dazhou", "dz"],
  资阳: ["ziyang", "zy"],
  眉山: ["meishan", "ms"],
  广安: ["guangan", "ga"],
  雅安: ["yaan", "ya"],
  巴中: ["bazhong", "bz"],
  广元: ["guangyuan", "gy"],
  攀枝花: ["panzhihua", "pzh"],
  三明: ["sanming", "sm"],
  莆田: ["putian", "pt"],
  龙岩: ["longyan", "ly"],
  南平: ["nanping", "np"],
  宁德: ["ningde", "nd"],
  三沙: ["sansha", "ss"],
  儋州: ["danzhou", "dz"],
  五指山: ["wuzhishan", "wzs"],
  琼海: ["qionghai", "qh"],
  文昌: ["wenchang", "wc"],
  万宁: ["wanning", "wn"],
  东方: ["dongfang", "df"],
  定安: ["dingan", "da"],
  屯昌: ["tunchang", "tc"],
  澄迈: ["chengmai", "cm"],
  临高: ["lingao", "lg"],
  白沙: ["baisha", "bs"],
  昌江: ["changjiang", "cj"],
  乐东: ["ledong", "ld"],
  陵水: ["lingshui", "ls"],
  保亭: ["baoting", "bt"],
  琼中: ["qiongzhong", "qz"],
  桂林: ["guilin", "gl"],
  北海: ["beihai", "bh"],
  柳州: ["liuzhou", "lz"],
  梧州: ["wuzhou", "wz"],
  钦州: ["qinzhou", "qz"],
  玉林: ["yulin", "yl"],
  百色: ["baise", "bs"],
  河池: ["hechi", "hc"],
  防城港: ["fangchenggang", "fcg"],
  贵港: ["guigang", "gg"],
  崇左: ["chongzuo", "cz"],
  来宾: ["laibin", "lb"],
  贺州: ["hezhou", "hz"],
  张家界: ["zhangjiajie", "zjj"],
  怀化: ["huaihua", "hh"],
  邵阳: ["shaoyang", "sy"],
  衡阳: ["hengyang", "hy"],
  株洲: ["zhuzhou", "zz"],
  湘潭: ["xiangtan", "xt"],
  岳阳: ["yueyang", "yy"],
  常德: ["changde", "cd"],
  益阳: ["yiyang", "yy"],
  郴州: ["chenzhou", "cz"],
  永州: ["yongzhou", "yz"],
  娄底: ["loudi", "ld"],
  湘西: ["xiangxi", "xx"],
  三亚: ["sanya", "sy"],
  襄阳: ["xiangyang", "xy"],
  宜昌: ["yichang", "yc"],
  荆州: ["jingzhou", "jz"],
  黄石: ["huangshi", "hs"],
  十堰: ["shiyan", "sy"],
  荆门: ["jingmen", "jm"],
  孝感: ["xiaogan", "xg"],
  黄冈: ["huanggang", "hg"],
  咸宁: ["xianning", "xn"],
  随州: ["suizhou", "sz"],
  恩施: ["enshi", "es"],
  仙桃: ["xiantao", "xt"],
  潜江: ["qianjiang", "qj"],
  天门: ["tianmen", "tm"],
  神农架: ["shennongjia", "snj"],
  鄂尔多斯: ["eerduosi", "eeds"],
  包头: ["baotou", "bt"],
  赤峰: ["chifeng", "cf"],
  通辽: ["tongliao", "tl"],
  呼伦贝尔: ["hulunbeier", "hlbe"],
  巴彦淖尔: ["bayannaoer", "byne"],
  乌兰察布: ["wulanchabu", "wlcb"],
  兴安盟: ["xinganmeng", "xam"],
  锡林郭勒: ["xilinguole", "xlgl"],
  阿拉善盟: ["alashanmeng", "alsm"],
  乌海: ["wuhai", "wh"],
  鞍山: ["anshan", "as"],
  抚顺: ["fushun", "fs"],
  本溪: ["benxi", "bx"],
  丹东: ["dandong", "dd"],
  锦州: ["jinzhou", "jz"],
  营口: ["yingkou", "yk"],
  阜新: ["fuxin", "fx"],
  辽阳: ["liaoyang", "ly"],
  盘锦: ["panjin", "pj"],
  铁岭: ["tieling", "tl"],
  朝阳: ["chaoyang", "cy"],
  葫芦岛: ["huludao", "hld"],
  大庆: ["daqing", "dq"],
  齐齐哈尔: ["qiqihaer", "qqhe"],
  牡丹江: ["mudanjiang", "mdj"],
  佳木斯: ["jiamusi", "jms"],
  鸡西: ["jixi", "jx"],
  双鸭山: ["shuangyashan", "sys"],
  伊春: ["yichun", "yc"],
  七台河: ["qitaihe", "qth"],
  鹤岗: ["hegang", "hg"],
  黑河: ["heihe", "hh"],
  绥化: ["suihua", "sh"],
  大兴安岭: ["daxinganling", "dxal"],
  蚌埠: ["bengbu", "bb"],
  芜湖: ["wuhu", "wh"],
  淮南: ["huainan", "hn"],
  马鞍山: ["maanshan", "mas"],
  淮北: ["huaibei", "hb"],
  铜陵: ["tongling", "tl"],
  安庆: ["anqing", "aq"],
  黄山: ["huangshan", "hs"],
  滁州: ["chuzhou", "cz"],
  阜阳: ["fuyang", "fy"],
  宿州: ["suzhou", "sz"],
  六安: ["liuan", "la"],
  亳州: ["bozhou", "bz"],
  池州: ["chizhou", "cz"],
  宣城: ["xuancheng", "xc"],
  沧州: ["cangzhou", "cz"],
  承德: ["chengde", "cd"],
  张家口: ["zhangjiakou", "zjk"],
  秦皇岛: ["qinhuangdao", "qhd"],
  唐山: ["tangshan", "ts"],
  廊坊: ["langfang", "lf"],
  衡水: ["hengshui", "hs"],
  保定: ["baoding", "bd"],
  邯郸: ["handan", "hd"],
  邢台: ["xingtai", "xt"],
  洛阳: ["luoyang", "ly"],
  开封: ["kaifeng", "kf"],
  平顶山: ["pingdingshan", "pds"],
  安阳: ["anyang", "ay"],
  鹤壁: ["hebi", "hb"],
  新乡: ["xinxiang", "xx"],
  焦作: ["jiaozuo", "jz"],
  濮阳: ["puyang", "py"],
  许昌: ["xuchang", "xc"],
  漯河: ["luohe", "lh"],
  三门峡: ["sanmenxia", "smx"],
  商丘: ["shangqiu", "sq"],
  周口: ["zhoukou", "zk"],
  驻马店: ["zhumadian", "zmd"],
  南阳: ["nanyang", "ny"],
  信阳: ["xinyang", "xy"],
  济源: ["jiyuan", "jy"],
  九江: ["jiujiang", "jj"],
  景德镇: ["jingdezhen", "jdz"],
  萍乡: ["pingxiang", "px"],
  新余: ["xinyu", "xy"],
  鹰潭: ["yingtan", "yt"],
  赣州: ["ganzhou", "gz"],
  吉安: ["jian", "ja"],
  宜春: ["yichun", "yc"],
  抚州: ["fuzhou", "fz"],
  上饶: ["shangrao", "sr"],
  潍坊: ["weifang", "wf"],
  淄博: ["zibo", "zb"],
  东营: ["dongying", "dy"],
  烟台: ["yantai", "yt"],
  威海: ["weihai", "wh"],
  日照: ["rizhao", "rz"],
  临沂: ["linyi", "ly"],
  德州: ["dezhou", "dz"],
  聊城: ["liaocheng", "lc"],
  滨州: ["binzhou", "bz"],
  菏泽: ["heze", "hz"],
  遵义: ["zunyi", "zy"],
  六盘水: ["liupanshui", "lps"],
  安顺: ["anshun", "as"],
  毕节: ["bijie", "bj"],
  铜仁: ["tongren", "tr"],
  黔西南: ["qianxinan", "qxn"],
  黔东南: ["qiandongnan", "qdn"],
  黔南: ["qiannan", "qn"],
  曲靖: ["qujing", "qj"],
  玉溪: ["yuxi", "yx"],
  保山: ["baoshan", "bs"],
  昭通: ["zhaotong", "zt"],
  丽江: ["lijiang", "lj"],
  普洱: ["puer", "pe"],
  临沧: ["lincang", "lc"],
  楚雄: ["chuxiong", "cx"],
  红河: ["honghe", "hh"],
  文山: ["wenshan", "ws"],
  西双版纳: ["xishuangbanna", "xsbn"],
  大理: ["dali", "dl"],
  德宏: ["dehong", "dh"],
  怒江: ["nujiang", "nj"],
  迪庆: ["diqing", "dq"],
  宝鸡: ["baoji", "bj"],
  咸阳: ["xianyang", "xy"],
  渭南: ["weinan", "wn"],
  延安: ["yanan", "ya"],
  汉中: ["hanzhong", "hz"],
  榆林: ["yulin", "yl"],
  安康: ["ankang", "ak"],
  商洛: ["shangluo", "sl"],
  铜川: ["tongchuan", "tc"],
  天水: ["tianshui", "ts"],
  嘉峪关: ["jiayuguan", "jyg"],
  金昌: ["jinchang", "jc"],
  白银: ["baiyin", "by"],
  武威: ["wuwei", "ww"],
  张掖: ["zhangye", "zy"],
  平凉: ["pingliang", "pl"],
  酒泉: ["jiuquan", "jq"],
  庆阳: ["qingyang", "qy"],
  定西: ["dingxi", "dx"],
  陇南: ["longnan", "ln"],
  临夏: ["linxia", "lx"],
  甘南: ["gannan", "gn"],
  海东: ["haidong", "hd"],
  海北: ["haibei", "hb"],
  黄南: ["huangnan", "hn"],
  海南: ["hainan", "hn"],
  果洛: ["guoluo", "gl"],
  玉树: ["yushu", "ys"],
  海西: ["haixi", "hx"],
  石嘴山: ["shizuishan", "szs"],
  吴忠: ["wuzhong", "wz"],
  固原: ["guyuan", "gy"],
  中卫: ["zhongwei", "zw"],
  克拉玛依: ["kelamayi", "klmy"],
  吐鲁番: ["tulufan", "tlf"],
  哈密: ["hami", "hm"],
  昌吉: ["changji", "cj"],
  博尔塔拉: ["boertala", "betl"],
  巴音郭楞: ["bayinguoleng", "bygl"],
  阿克苏: ["akesu", "aks"],
  克孜勒苏: ["kezilesu", "kzls"],
  喀什: ["kashi", "ks"],
  和田: ["hetian", "ht"],
  伊犁: ["yili", "yl"],
  塔城: ["tacheng", "tc"],
  阿勒泰: ["aletai", "alt"],
  石河子: ["shihezi", "shz"],
  阿拉尔: ["alaer", "ale"],
  图木舒克: ["tumushuke", "tmsk"],
  五家渠: ["wujiaqu", "wjq"],
  北屯: ["beitun", "bt"],
  铁门关: ["tiemenguan", "tmg"],
  双河: ["shuanghe", "sh"],
  可克达拉: ["kekedala", "kkdl"],
  昆玉: ["kunyu", "ky"],
  胡杨河: ["huyanghe", "hyh"],
  新星: ["xinxing", "xx"],
  白杨: ["baiyang", "by"],
};

/**
 * 检查关键词是否匹配城市（支持中文、拼音首字母、全拼）
 */
export function matchCityPinyin(keyword: string, cityName: string): boolean {
  if (!keyword || !cityName) {
    return false;
  }
  
  const normalizedKeyword = keyword.toLowerCase().trim();
  const normalizedCity = cityName.toLowerCase().trim();
  
  // 1. 直接匹配中文城市名
  if (normalizedCity.includes(normalizedKeyword) || normalizedKeyword.includes(normalizedCity)) {
    return true;
  }
  
  // 2. 匹配拼音映射
  const pinyins = cityPinyinMap[cityName];
  if (pinyins) {
    for (const pinyin of pinyins) {
      if (pinyin.includes(normalizedKeyword) || normalizedKeyword.includes(pinyin)) {
        return true;
      }
      // 支持拼音首字母匹配（如 "bj" 匹配 "beijing"）
      if (normalizedKeyword.length <= 3 && pinyin.startsWith(normalizedKeyword)) {
        return true;
      }
    }
  }
  
  return false;
}

/**
 * 根据拼音关键词获取匹配的城市列表
 */
export function getCitiesByPinyin(keyword: string, allCities: string[]): string[] {
  if (!keyword || keyword.trim().length === 0) {
    return allCities;
  }
  
  const normalizedKeyword = keyword.toLowerCase().trim();
  return allCities.filter(city => matchCityPinyin(normalizedKeyword, city));
}


